# Generated by Django 4.2 on 2023-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='matricule',
            field=models.CharField(editable=False, max_length=5, unique=True, verbose_name='matricule'),
        ),
    ]
