# Generated by Django 4.2 on 2023-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_consultant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='matricule',
            field=models.CharField(max_length=5, unique=True, verbose_name='matricule'),
        ),
    ]
