# Generated by Django 4.2 on 2023-04-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_consultant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.consultant'),
        ),
    ]
