# Generated by Django 4.2 on 2023-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_consultant_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='clients_number',
            field=models.IntegerField(null=True, verbose_name='Nombre de clients'),
        ),
    ]
