# Generated by Django 4.2 on 2023-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_consultant_clients_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='clients_number',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='matricule',
            field=models.CharField(max_length=5, unique=True, verbose_name='Matricule'),
        ),
    ]
