# Generated by Django 4.2 on 2023-05-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
