# Generated by Django 4.2 on 2023-05-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_consultant_clients_number_and_more'),
        ('eshop', '0011_rename_comment_ordercomment_body_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderComment',
            new_name='Comment',
        ),
    ]
