# Generated by Django 4.2 on 2023-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_rename_ordercomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
